name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  DEPLOY_USERNAME: ingwarsw
  DEPLOY_SERVER_ID: bintray-ingwarsw-org.eu.ingwar.tools
    
jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        profile: 
          - test-wildfly-managed,coveralls-coverage
          - test-wildfly-managed-domain
          - test-jboss-managed-domain
          - test-jboss-managed
          - test-glassfish-embeded
    
    env:
      PROFILE:
        ${{ matrix.profile }}
    
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up JDK 1.8
        uses: renatoathaydes/setup-java-sdkman@2.1.1
        with:
          java-version: 8.0.265-zulu
      - name: Build with Maven
        run: travis/travis.py --fetch
      - name: Test with Maven
        run: travis/travis.py --test
