name: CI

on:
  push:
    branches: [ master ]
    tags:
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        profile: 
          - test-wildfly-managed,coveralls-coverage
          - test-wildfly-managed-domain
          - test-jboss-managed-domain
#          - test-jboss-managed
#          - test-glassfish-embeded
    
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Build
        run: mvn install --batch-mode -T4 -DskipTests=true
      - name: Test
        run: mvn test --batch-mode -T4 -P${{ matrix.profile }}
  
  test_suites:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        suite:
          - junit5
    
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Set env
        run: echo "AS_VERSION=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)" >> $GITHUB_ENV
      - name: Build
        run: mvn install --batch-mode -T4 -DskipTests=true
      - name: Run test suite
        run: mvn test --batch-mode -Dversion.arquillian_suite=${{ env.AS_VERSION }}
        working-directory: ./test-suites/${{ matrix.suite }}

  publish:
    runs-on: ubuntu-latest
    needs: [build, test_suites]
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 8
          server-id: bintray-ingwarsw-org.eu.ingwar.tools
          server-username: BINTRAY_USERNAME
          server-password: BINTRAY_API_KEY
      - name: Publish to Apache Maven Central
        run: mvn deploy --batch-mode
        env:
          BINTRAY_USERNAME: ingwarsw
          BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
